import AbstractAttentionCrudRouterImpl from './AbstractAttentionCrudRouterImpl'
import IAttentionCrudServiceMongoImpl from './IAttentionCrudServiceMongoImpl'

export const resourceCrudMongoServiceInstance = new IAttentionCrudServiceMongoImpl()
export const resouceCrudRouterImplInstance = new AbstractAttentionCrudRouterImpl(resourceCrudMongoServiceInstance)
